### ISSUE TITLE
Meeting Pane not updated when using meet command

### ISSUE THREAD

**Issue by Zenious** [CS2103-AY1819S1-W17-3/main#129]
When successfully execute meet command, the pane does not reflect the changes. Only group pane reflects the new changes.

![image](https://user-images.githubusercontent.com/7553066/47452361-ae409a80-d7fc-11e8-9b15-f88cb4e6df00.png)

@jeffreyooi advice?

**Comment by jeffreyooi** [comment]
@Zenious MeetingList is created only at the beginning by streaming from all groups and collect them because there isn't a list to hold all meetings. There are 2 approaches to fix this:

1. Add a list in `Model` to hold all meetings and bind using that list so that any updates (e.g. add / remove) will also update the list automatically by the UI
2. Use events to notify UI that meeting has changed and needs to stream from groups to collect updated information

Personally I would opt for the first option. You think it is ok?

**Comment by Zenious** [comment]
@jeffreyooi I believe both options provided by you sound feasible. 2nd option will be cleaner IMO as MeetingList will be only used by UI and should be contained in the UI component instead. However, the first option provides us with flexibility in a situation that we may need to use MeetingList in the future for other features.

I think we shall go ahead with the first option for now!
